### ISSUE TITLE
Aktualizace

### ISSUE THREAD

**Issue by jaro-jaro** [jaro-jaro/DPMCB#132]
Při aktualizaci dat bez internetu se ukáže tohle:
![Screenshot_2023-04-04-21-47-35-778_cz.jaro.dpmcb.jpg](https://user-images.githubusercontent.com/90213952/229903709-f21c3452-fa59-40c2-b413-c4a3d33d0672.jpg)

a nic to nedělá. Chtělo by to zakázat aktualizace bez internetu

**Comment by rblaha15** [comment]
> Chtělo by to zakázat aktualizace bez internetu

Asi jo. Dává to smysl
