### ISSUE TITLE
Vybírání

### ISSUE THREAD

**Issue by jaro-jaro** [jaro-jaro/DPMCB#135]
Ve vybírátoru nefunguje rychlý vybírání pro zastávky s jinou obcí než Budějce. #79 asi nefunguje

**Comment by jaro-jaro** [comment]
respektive je #79 daný jako dokončený, ale v rblaha/stahovani-z-cisjr#1, to je pořád otevřený

**Comment by rblaha15** [comment]
Aha.... Tam není mezera, tudíž se to nepovažuje jako nové slovo

**Comment by rblaha15** [comment]
Ano, ovlivňuje to aplikaci, ale nevyžaduje to žádnou změnu jejího kódu, proto ti to musím zavřít. Přesto to ale dám do #98
