### ISSUE TITLE
[1.1.0-alpha.2...1.1.0-pre.3] Zjednodušit

### ISSUE THREAD

**Issue by 0ndra0** [jaro-jaro/DPMCB#180]
U zjednodušení se nepíše za jak dlouho bus pojede, ale před jakou chvílí odjel
![Screenshot_2023-04-18-11-43-00-865_cz.jaro.dpmcb.jpg](https://user-images.githubusercontent.com/130213334/232738751-b251656c-2ed3-4d00-a7dc-46761880e142.jpg)

1.1.0-pre.1

**Comment by rblaha15** [comment]
Aha... Asi tuším co s tím je... Odčítám A od B místo B od A
