### ISSUE TITLE
[1.1.0-alpha.2...1.1.0-pre.4] Průběžné aktualizování 

### ISSUE THREAD

**Issue by 0ndra0** [jaro-jaro/DPMCB#182]
Jakmile otevřu detail spoje, tak se sice zdá, že je všechno správně (až na to, že se nevykresluje čára vpravo a zůstává pořád u poslední zastávky)
![Screenshot_2023-04-18-09-48-52-515_cz.jaro.dpmcb.jpg](https://user-images.githubusercontent.com/130213334/232740783-e5d24357-2554-4a77-a05a-b33daeff5821.jpg)
Když ale mám ten bus otevřenej dýl (nejlíp je to vidět, když v něm jedu), tak si všimnu, že se neaktualizuje
![IMG_20230418_115623.jpg](https://user-images.githubusercontent.com/130213334/232742090-695c637c-ac7a-498f-9e93-a63ec08d1231.jpg)
Teda ne tak úplně, kousek před tim, než jsem udělal tenhle screenshot, tak ta devítka měla 1 minutu zpoždění, ale na Vltavě to dohnala (mimochodem ta devítka byla 406 s Vlastou). To je zajímavý, že měla minutu, ale na tom screenshotu nemá, protože se to potom, co jsme vyjeli z Vltavy zaktualizovalo, ale jenom zpoždění. Na druhou stranu, když jsem jel 14kou se zpožděním asi 3-5 minut, který se měnilo, tak se to v aplikaci neměnilo
![Screenshot_2023-04-18-09-56-00-021_cz.jaro.dpmcb.jpg](https://user-images.githubusercontent.com/130213334/232744189-7d5cf75a-db25-49c6-930b-d3888d6d6e00.jpg)
![Screenshot_2023-04-18-10-05-42-904_cz.jaro.dpmcb.jpg](https://user-images.githubusercontent.com/130213334/232744190-609679f9-3296-41b1-8ef0-dca7ffb661a4.jpg)
Když jsem opustil detail spoje a šel třeba na oblíbený, tak se to taky neaktualizovalo ani tam ani když jsem znova otevřel detail spoje.Ale když jsem aplikaci vypnul a znova zapnul, tak všechno fungovalo, dokud jsem nezapl detail spoje, a pak ten spoj přestal fungovat. Když jsem zo stejný zkoušel teď, tak všechno normálně fungovalo, i když jsem vypnul wifi a zapnul data, tak všechno funguje, ale bylo to dost divný a nechápu, jak se to mohlo stát, protože teď to funguje

**Comment by rblaha15** [comment]
sus

**Comment by rblaha15** [comment]
Chvîli jsem sledoval tenhle spoj a jediný co mi nefunguje, je posouvání busu - skáče mezi zastávkama, což ovšem platí i offline! To je asi to co jsi myslel tím

> že se nevykresluje čára vpravo a zůstává pořád u poslední zastávky

![Screenshot_20230418-203514](https://user-images.githubusercontent.com/72446087/232872616-cbd947ec-4cce-475e-84df-72fa6a112223.png)
![Screenshot_20230418-203556](https://user-images.githubusercontent.com/72446087/232872626-35d9e511-2b09-4dfe-a98e-9906c728c85a.png)
![Screenshot_20230418-203610](https://user-images.githubusercontent.com/72446087/232872630-bbf2ecd9-bec5-4574-a893-48d3d95039a9.png)
![Screenshot_20230418-203616](https://user-images.githubusercontent.com/72446087/232872651-eeb52777-af2c-461f-8306-fb167096e10c.png)
![Screenshot_20230418-203744](https://user-images.githubusercontent.com/72446087/232872670-76683040-9a3c-47b4-9e02-ebbbfcca7dd6.png)
![Screenshot_20230418-203847](https://user-images.githubusercontent.com/72446087/232872676-fa9f4343-ca99-4709-811c-0041f4022239.png)
![Screenshot_20230418-203926](https://user-images.githubusercontent.com/72446087/232872687-35190842-dafa-4712-99c9-3ccbac9d7ea0.png)

Myslím si, že chyba bude od v1.1.0-alpha.2 (#159) nejspíš někde [tady](https://github.com/jaro-jaro/DPMCB/blob/main/app/src/main/java/cz/jaro/dpmcb/ui/spoj/DetailSpojeViewModel.kt#L67-L75)

**Comment by rblaha15** [comment]
Možná jsem zase prohodil to Duration.between, jako v #181

**Comment by rblaha15** [comment]
Rozdělím tuto issue na 3 části:
1. Bus skáče po celých zastávkách, nejede plynule – to bylo opraveno v #182
2. Bus se freezene a nehodlá se aktualizovat – nutno restartovat aplikaci – nově #
3. I po opravení v #182 stále problém přetrvává u výchozí zastávky – nově #
