### ISSUE TITLE
Zlepšení přes

### ISSUE THREAD

**Issue by 0ndra0** [jaro-jaro/DPMCB#187]
V odjezdech při filtrování "Jede přes" bych to filtroval tak, že to na tu zastávku teprve pojede po tý zastávce, kterou máš otevřenou

**Comment by rblaha15** [comment]
Taky mě to napadlo, nevěděl jsem ale, jestli bychom to chtěli

**Comment by rblaha15** [comment]
Bude to asi v 1.2

**Comment by 0ndra0** [comment]
> Taky mě to napadlo, nevěděl jsem ale, jestli bysme to chtěli

Já si myslim, že bysme to chtěli, protože to, jak je to teď moc nedává smysl a navíc nemám, jak si jednoduše u odjezdů vyfiltrovat jeden směr
