### ISSUE TITLE
Přidat možnot vytvoření zkratek z jednotlivých obrazovek

### ISSUE THREAD

**Issue by rblaha15** [jaro-jaro/DPMCB#209]
Zkratka by obsahovala všechna nastavení dané obrazovky

**Comment by rblaha15** [comment]
Aktuálně jsou takovéhle možnosti:

`/jizdni_rady/{cisloLinky}/{zastavka}/{pristiZastavka}`
`/mapa`
`/oblibene`
`/odjezdy/{zastavka}?cas={cas}&linka={linka}&pres={pres}`
`/prave_jedouci?filtry={filtry}`
`/spoj/{spojId}`
`/vybirator/{typ}?cisloLinky={cisloLinky}&zastavka={zastavka}`

**Comment by 0ndra0** [comment]
jo, to jde, asi bych to dal vpravo na top bar na každou obrazovku
