### ISSUE TITLE
Špatný id

### ISSUE THREAD

**Issue by 0ndra0** [jaro-jaro/DPMCB#210]
Když člověk do hledání spoje podle id zadá úplně nesmyslný znaky, tak aplikace spadne

**Comment by rblaha15** [comment]
Zajímavé je, že tam můžeš dostat až 3 různý chyby: `IndexOutOfBoundsException`, `NumberFormatException` a `NullPointerException`

**Comment by rblaha15** [comment]
Proč jsi to znovuotevřel? Už to je přeci opravený @0ndra0
