### ISSUE TITLE
Padá ve vybírání

### ISSUE THREAD

**Issue by 0ndra0** [jaro-jaro/DPMCB#224]
když si člověk změní datum, tak že nic nejede a otevře odjezdy nebo jř, tak nic nevidí a když klikne enter, tak aplikace spadne

**Comment by 0ndra0** [comment]
Když ale jako první otevřu třeba odjezdy a až pak nastavim blbý datum, tak se objeví tohle

![Screenshot_2023-05-16-17-21-11-046_cz.jaro.dpmcb.jpg](https://github.com/jaro-jaro/DPMCB/assets/130213334/107cb2ab-4f60-40a3-8b5a-7881e8a332da)

**Comment by rblaha15** [comment]
Popravdě, stačí napsat nějakej blbábol, aby byl seznam prázdný:
![Screenshot_20230517-065835](https://github.com/jaro-jaro/DPMCB/assets/72446087/cdeb4737-f37d-4b2a-88a9-def7875d88f9)
