### ISSUE TITLE
Zastávka je bus dvakrát

### ISSUE THREAD

**Issue by jaro-jaro** [jaro-jaro/DPMCB#23]
Když jede bus dvakrát na stejnou zastávku, tak v jízdních tlřádech z té zastávky se odjezdy neřadí podle času
![Screenshot_2023-01-06-15-12-15-020_cz jaro dpmcb](https://user-images.githubusercontent.com/90213952/211029424-0a1676b4-c916-4fe6-8265-7b61b80713b4.jpg)

**Comment by rblaha15** [comment]
Jo, jakože je to špatně seřazený, že?

**Comment by jaro-jaro** [comment]
Jakože tam je třeba 8:14, 8:34, 8:54, 8:02, 8:22 a 8:42

**Comment by rblaha15** [comment]
A má být 02, 14, 22, 34, 42, 54, že

**Comment by rblaha15** [comment]
Snad opraveno v #26
