### ISSUE TITLE
V detailu spoje a v odjezdech něco přelejzá

### ISSUE THREAD

**Issue by rblaha15** [jaro-jaro/DPMCB#234]
Dokonce i menu

**Comment by 0ndra0** [comment]
![Screenshot_2023-05-23-08-17-56-386_cz.jaro.dpmcb.jpg](https://github.com/jaro-jaro/DPMCB/assets/130213334/cd2c778f-685a-4242-b493-b0e8d3c69d51)

**Comment by 0ndra0** [comment]
![Screenshot_2023-05-24-11-15-06-161_cz.jaro.dpmcb.jpg](https://github.com/jaro-jaro/DPMCB/assets/130213334/fa5dd5ce-cd9a-4711-8268-905372b98303)
