### ISSUE TITLE
Ještě pár chyb v online datech

### ISSUE THREAD

**Issue by 0ndra0** [jaro-jaro/DPMCB#244]
Homole, Nové Homole, Korosecký dvůr

![Screenshot_2023-05-24-10-10-58-310_cz.jaro.dpmcb.jpg](https://github.com/jaro-jaro/DPMCB/assets/130213334/22f990f0-0f62-4f88-b6d0-3afe2cd6d06b)

**Comment by rblaha15** [comment]
Partří do [jaro-jaro/stahovani-z-cisjr](https://github.com/jaro-jaro/stahovani-z-cisjr)
