### ISSUE TITLE
Barvičkovatý ikonky

### ISSUE THREAD

**Issue by 0ndra0** [jaro-jaro/DPMCB#306]
nedávalo by smysl nějak trošku jinak výraznějc udělat tu ikonku nízkopodlažnosti, pokus bude jiná než je plánovaná, třeba červeně, pokud je vysokopodlažní na nízkopodlažním spoji (to se snad nikdy nestane, ale může) a zeleně, když je to naopak 
vejcuc - ikonka v detailu spoje může být zelená, červená nebo primary

vozíčkáře se občas (moc často, včera na mě za tu dobu, co jsem pozoroval jeden spoj asi třikrát) objeví vozík
řešení - remember { ikonka } (dát ikonku od rememberu)

**Comment by rblaha15** [comment]
Ono to nefunguje úplně přesně tak, ale skoro jo
