### ISSUE TITLE
Klávesnice se neROzevře

### ISSUE THREAD

**Issue by rblaha15** [jaro-jaro/DPMCB#34]

**Comment by jaro-jaro** [comment]
Zázračně opraveno v https://github.com/jaro-jaro/DPMCB/commit/535ba8b56ea34aeaed2851517867f5687d7fdeb6

**Comment by jaro-jaro** [comment]
Zázračně opraveno v https://github.com/jaro-jaro/DPMCB/commit/535ba8b56ea34aeaed2851517867f5687d7fdeb6

**Comment by rblaha15** [comment]
ÁÁÁÁÁÁÁÁÁÁÁÁÁÁÁháááááááááááááááááááá

**Comment by rblaha15** [comment]
MAǦIK!

**Comment by jaro-jaro** [comment]
reálně stačilo nahradit 45 znaků za 4 jiný, naprosto to nechápu

**Comment by jaro-jaro** [comment]
Proč tolik?

**Comment by rblaha15** [comment]
45?

**Comment by jaro-jaro** [comment]
já jsem psal 5 a pak se to samo změnilo na 45, tak jsem myslel, žes to změnil
