### ISSUE TITLE
Nesouhlasí jména s dopravou na jihu  ** NEPOTŘEBA S #78

### ISSUE THREAD

**Issue by jaro-jaro** [jaro-jaro/DPMCB#47]
Všechna jména zastávek se neshodují s tima, co používá doprava na jihu. Je potřeba přidat výjimky i k těm, co nejsou konečný.

**Comment by rblaha15** [comment]
Pokračování z 
[] #2

**Comment by rblaha15** [comment]
Již není potřeba s #78
