### ISSUE TITLE
Čárky a tečky

### ISSUE THREAD

**Issue by jaro-jaro** [jaro-jaro/DPMCB#79]
U názvů zastávek chybí za tečkama a čárkama mezera (neplatí pro zastávky Homole, Zemědělská technika, Homole, Diagnostický ústav, Litvínovice,Mokré, Zastávka a  Roudné rozcestí)

**Comment by rblaha15** [comment]
Chyba v cisjr; podle mě patří spíše do rblaha15/stahovani-z-cisjr
