### ISSUE TITLE
Při načítání nových dat nefunguje darkmode

### ISSUE THREAD

**Issue by jaro-jaro** [jaro-jaro/DPMCB#81]
![Screenshot_2023-03-01-20-03-50-632_cz.jaro.dpmcb.debug.jpg](https://user-images.githubusercontent.com/90213952/222239264-56063e25-726f-400c-89d4-ad2816bcfebc.jpg)

**Comment by rblaha15** [comment]
O tom vím

**Comment by rblaha15** [comment]
Opraveno, bude v #88
