### ISSUE TITLE
Nefunguje tlačítko aktualizovat data

### ISSUE THREAD

**Issue by jaro-jaro** [jaro-jaro/DPMCB#82]
Tlačítko pro aktualizaci dat v nastavení funguje tak, že sice dá stahovat nový data, ale v průběhu se otevře obrazovka nastavení a všechna data se smažou

**Comment by jaro-jaro** [comment]
Když jsem otevřel aplikaci znova a dal aktualizovat data, tak to fungovalo

**Comment by rblaha15** [comment]
Nemůžu reprodukovat, mě funguje vpořádku
