### ISSUE TITLE
V oblíbených nefunguje čas cílové zastávky

### ISSUE THREAD

**Issue by jaro-jaro** [jaro-jaro/DPMCB#83]
Nevim, proč používat odděleně čas příjezdu a odjezdu #84

![Screenshot_2023-03-01-20-11-02-093_cz.jaro.dpmcb.debug.jpg](https://user-images.githubusercontent.com/90213952/222240679-934339cc-8d38-41f7-a33c-a67ee9de96fe.jpg)

**Comment by jaro-jaro** [comment]
![Screenshot_2023-03-01-20-11-02-093_cz.jaro.dpmcb.debug.jpg](https://user-images.githubusercontent.com/90213952/222246203-ac4e66d1-b184-4433-90fb-b61253a82611.jpg)

**Comment by rblaha15** [comment]
Opraveno, bude v #88
