### ISSUE TITLE
(Ne)využívání času přijezdu a odjezdu v detailu spoje

### ISSUE THREAD

**Issue by jaro-jaro** [jaro-jaro/DPMCB#84]
Za mě nedává smysl psát jak čas příjezdu, tak čas odjezdu na zastávku. Psal bych tam jenom jeden čas, ty časy jsou navíc ůplně vždycky stejný, pokud jsou oba

Za mě jsou ty dva časy jenom matoucí
![Screenshot_2023-03-01-20-13-16-830_cz.jaro.dpmcb.debug.jpg](https://user-images.githubusercontent.com/90213952/222242155-83606b2f-502d-47ee-b495-2810e368c34f.jpg)

Tady je vidět, že na nádraží ten bus stejně nemá žádnej pobyt
![Screenshot_2023-03-01-20-19-38-627_cz.jaro.dpmcb.debug.jpg](https://user-images.githubusercontent.com/90213952/222242470-5f1f1eac-8827-4610-b30c-e5fc56de092f.jpg)

**Comment by rblaha15** [comment]
Dobrá – v datech to zůstane, ale nebudeme to zobrazovat

**Comment by jaro-jaro** [comment]
jj, tak mi to přijde nejlepší, a teoreticky by se to mohlo po delší době, kdybysme to nepotřebovali zrušit

**Comment by rblaha15** [comment]
> Tady je vidět, že na nádraží ten bus stejně nemá žádnej pobyt ![Screenshot_2023-03-01-20-19-38-627_cz.jaro.dpmcb.debug.jpg](https://user-images.githubusercontent.com/90213952/222242470-5f1f1eac-8827-4610-b30c-e5fc56de092f.jpg)

Tohle je fakt divný, ale za to my nemůžem...

**Comment by rblaha15** [comment]
Hotovo - bude v #88
