### ISSUE TITLE
Duální spoje

### ISSUE THREAD

**Issue by jaro-jaro** [jaro-jaro/DPMCB#85]
Jenom to, že je několik případů, kdy je jeden spoj dvakrát, ale s jiným id

![Screenshot_2023-03-01-20-27-18-656_cz.jaro.dpmcb.debug.jpg](https://user-images.githubusercontent.com/90213952/222244233-de8e8afc-06f1-4a6c-ad9c-5593254224ef.jpg)

![Screenshot_2023-03-01-20-27-24-646_cz.jaro.dpmcb.debug.jpg](https://user-images.githubusercontent.com/90213952/222244234-7a6af6a8-e7b2-4d9a-848f-2687af788c6a.jpg)

**Comment by rblaha15** [comment]
Co když je s jiným VDP

**Comment by rblaha15** [comment]
- #87

**Comment by jaro-jaro** [comment]
tak, že jsem dal dnešní odjezdy od Koně, zapomněl jsem tam dát screenshot, tak tady je
![Screenshot_2023-03-01-20-16-45-368_cz.jaro.dpmcb.debug.jpg](https://user-images.githubusercontent.com/90213952/222345599-31b0fd66-c1af-47e8-8bd2-48600defd729.jpg)

**Comment by jaro-jaro** [comment]
![Screenshot_2023-03-02-07-15-44-624_cz.jaro.dpmcb.debug.jpg](https://user-images.githubusercontent.com/90213952/222346522-88113f5e-3106-4ef3-9496-f25600c2697c.jpg)

**Comment by rblaha15** [comment]
Takže... 
To že je to zduplovaný v odjezdech a JŘ je díky
- #86

To, že JSOU dva je naprosto vpořádku a je to tak správně

To, že je od sebe nerozeznáš řeší
- #87
