### ISSUE TITLE
Víkendy

### ISSUE THREAD

**Issue by jaro-jaro** [jaro-jaro/DPMCB#86]
O víkendech funguje jenom 13ka a 7ka, jiný linky prostě nejsou

![Screenshot_2023-03-01-20-31-00-647_cz.jaro.dpmcb.debug.jpg](https://user-images.githubusercontent.com/90213952/222245001-c3dcf250-addc-41da-bc2e-985dd32fa3ba.jpg)

![Screenshot_2023-03-01-20-34-59-709_cz.jaro.dpmcb.debug.jpg](https://user-images.githubusercontent.com/90213952/222245546-7bcf6a54-9a65-49cc-95fd-1dc96255d56d.jpg)

**Comment by rblaha15** [comment]
Sus

**Comment by rblaha15** [comment]
Opraveno, bude v #88
