### ISSUE TITLE
Linka v právě jedoucích

### ISSUE THREAD

**Issue by jaro-jaro** [jaro-jaro/DPMCB#91]
Asi to nemusim úplně komentovat
![Screenshot_2023-03-02-22-15-26-507_cz.jaro.dpmcb.debug.jpg](https://user-images.githubusercontent.com/90213952/222557454-4bc8236c-ba11-471c-b367-ba9ca88c4e34.jpg)

**Comment by rblaha15** [comment]
Opraveno, bude v #88
