### ISSUE TITLE
Prázdný časkódy

### ISSUE THREAD

**Issue by jaro-jaro** [jaro-jaro/DPMCB#92]
Když jsou prázdný časkódy, tak by se hodilo tam nic nepsat
![Screenshot_2023-03-02-22-12-54-755_cz.jaro.dpmcb.debug.jpg](https://user-images.githubusercontent.com/90213952/222558232-f7700eb6-5b99-45f1-8488-1cbda21e8ace.jpg)

**Comment by rblaha15** [comment]
Opraveno, bude v #88

**Comment by rblaha15** [comment]
Stále neopraveno :(
