### ISSUE TITLE
Časkódy s prosincem

### ISSUE THREAD

**Issue by jaro-jaro** [jaro-jaro/DPMCB#93]
Když je v časkódech prosinec 2023, tak se tam dá 0. měsíc 2024 (27. - 29. 12. 2023 jsou Vánoční prázdniny)

![Screenshot_2023-03-02-22-13-17-705_cz.jaro.dpmcb.debug.jpg](https://user-images.githubusercontent.com/90213952/222559484-4ce56777-f254-45a3-a158-29375f42e01c.jpg)

**Comment by rblaha15** [comment]
sus
